version: "3.3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    image: ci.tno.nl/ssi-lab/ssi-service-backend
    build:
      context: backend
      dockerfile: Dockerfile.prod
    environment:
      - SSI_SERVER_URL
      - IRMASERVER_URL
      - DATABASE_URL
      - ACAPY_ADMIN_URL
      - ACAPY_INDY_DID
      - TRINSIC_ADMIN_URL
      - TRINSIC_API_KEY
      - DATAKEEPER_API_URL
      - DATAKEEPER_API_KEY
    depends_on:
      - db
    networks:
      - proxy
      - internal
    labels:
      traefik.enable: "true"
      traefik.http.routers.ssi-backend.tls.certresolver: letsencrypt
      traefik.http.routers.ssi-backend.tls.options: safeTLSOptions@file
      traefik.http.routers.ssi-backend.middlewares: securityHeaders@file
      traefik.http.routers.ssi-backend.rule: Host(`service.ssi-lab.nl`) && PathPrefix(`/api`, `/socket.io`)

  frontend:
    image: ci.tno.nl/ssi-lab/ssi-service-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    environment:
      - SSI_SERVER_URL
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.ssi-frontend-insecure.rule: Host(`service.ssi-lab.nl`)
      traefik.http.routers.ssi-frontend-insecure.middlewares: redirectToHttps@file,securityHeaders@file
      traefik.http.routers.ssi-frontend.tls.certresolver: letsencrypt
      traefik.http.routers.ssi-frontend.tls.options: safeTLSOptions@file
      traefik.http.routers.ssi-frontend.middlewares: securityHeaders@file
      traefik.http.routers.ssi-frontend.rule: Host(`service.ssi-lab.nl`)

  irma:
    image: ci.tno.nl/ssi-lab/irma-server
    build: irma
    environment:
      - IRMASERVER_URL
      - IRMASERVER_VERBOSE
      - IRMASERVER_PRODUCTION
    volumes:
      - irma-schemes:/root/.local/share/irma/irma_configuration
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.ssi-irma-insecure.rule: Host(`irma.ssi-lab.nl`)
      traefik.http.routers.ssi-irma-insecure.middlewares: redirectToHttps@file,securityHeaders@file
      traefik.http.routers.ssi-irma.tls.certresolver: letsencrypt
      traefik.http.routers.ssi-irma.tls.options: safeTLSOptions@file
      traefik.http.routers.ssi-irma.middlewares: securityHeaders@file
      traefik.http.routers.ssi-irma.rule: Host(`irma.ssi-lab.nl`)

  acapy:
    image: ci.tno.nl/ssi-lab/aca-py-server
    build: acapy
    # FIXME: Can't figure out how to pass IT setttings using ENV vars
    # command: start --inbound-transport $ACAPY_INBOUND_TRANSPORT
    command: start --inbound-transport http 0.0.0.0 9000 --admin 0.0.0.0 9001 --auto-provision
    networks:
      - proxy
      - internal
    environment:
      - ACAPY_LABEL
      - ACAPY_ENDPOINT
      - ACAPY_GENESIS_URL
      - ACAPY_WALLET_SEED
      - ACAPY_WALLET_KEY
      - ACAPY_WALLET_NAME
      - ACAPY_WALLET_TYPE
      # FIXME: Passed using command above
      # - ACAPY_INBOUND_TRANSPORT
      - ACAPY_OUTBOUND_TRANSPORT
      # - ACAPY_ADMIN
      - ACAPY_ADMIN_INSECURE_MODE
      - ACAPY_WEBHOOK_URL
      - ACAPY_DEBUG_CONNECTIONS
      - ACAPY_DEBUG_CREDENTIALS
      - ACAPY_AUTO_ACCEPT_INVITES
      - ACAPY_AUTO_ACCEPT_REQUESTS
      - ACAPY_AUTO_RESPOND_MESSAGES
      - ACAPY_AUTO_RESPOND_CREDENTIAL_PROPOSAL
      - ACAPY_AUTO_RESPOND_CREDENTIAL_OFFER
      - ACAPY_AUTO_RESPOND_CREDENTIAL_REQUEST
      - ACAPY_AUTO_RESPOND_PRESENTATION_PROPOSAL
      - ACAPY_AUTO_RESPOND_PRESENTATION_REQUEST
      - ACAPY_AUTO_STORE_CREDENTIAL
      - ACAPY_AUTO_VERIFY_PRESENTATION
    volumes:
      # - ./indy-logs:/home/indy/logs
      - indy-client:/home/indy/.indy_client
    labels:
      traefik.enable: "true"
      traefik.http.routers.ssi-acapy-insecure.rule: Host(`acapy.ssi-lab.nl`)
      traefik.http.routers.ssi-acapy-insecure.middlewares: redirectToHttps@file,securityHeaders@file
      traefik.http.routers.ssi-acapy.tls.certresolver: letsencrypt
      traefik.http.routers.ssi-acapy.tls.options: safeTLSOptions@file
      traefik.http.routers.ssi-acapy.middlewares: securityHeaders@file
      traefik.http.routers.ssi-acapy.rule: Host(`acapy.ssi-lab.nl`)

volumes:
  irma-schemes:
  db-data:
  indy-client:

networks:
  internal:
  proxy:
    external: true
